# -*- coding: utf-8 -*-
"""assignment_21_pm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQsRgvnobJmQ872VWVqrSoISfIYqSssR
"""

import numpy as np
import matplotlib.pyplot as plt

np.random.seed(0)
X_reg = np.linspace(0, 10, 50)
y_reg = 2 * X_reg + 3 + np.random.randn(50)
X_clf = np.linspace(0, 10, 50)
y_clf = np.where(X_clf > 5, 1, 0)

coeffs = np.polyfit(X_reg, y_reg, 1)
y_pred = np.polyval(coeffs, X_reg)

plt.scatter(X_reg, y_reg)
plt.plot(X_reg, y_pred, color='red')
plt.title("Regression")
plt.show()

threshold = 5
y_pred_clf = np.where(X_clf > threshold, 1, 0)

plt.scatter(X_clf, y_clf)
plt.title("Classification")
plt.show()

m = 2
c = 3

y_pred_manual = m * X_reg + c
y_pred_manual

mse = np.mean((y_reg - y_pred_manual) ** 2)
print("MSE:", mse)

threshold = 5
y_pred = np.where(X_clf > threshold, 1, 0)

accuracy = np.mean(y_pred == y_clf)
print("Accuracy:", accuracy)

import numpy as np
import matplotlib.pyplot as plt


np.random.seed(0)
X = np.linspace(0, 10, 30)
y = np.sin(X) + np.random.randn(30) * 0.3


def fit_model(degree):
    coeffs = np.polyfit(X, y, degree)
    y_pred = np.polyval(coeffs, X)
    return y_pred

y_pred_1 = fit_model(1)
y_pred_2 = fit_model(2)
y_pred_5 = fit_model(5)

plt.scatter(X, y, label="Data")

plt.plot(X, y_pred_1, label="Degree 1")
plt.plot(X, y_pred_2, label="Degree 2")
plt.plot(X, y_pred_5, label="Degree 5")

plt.legend()
plt.title("Bias-Variance Tradeoff")
plt.show()

degrees = [1, 2, 3, 4, 5]
errors = []

for d in degrees:
    coeffs = np.polyfit(X, y, d)
    y_pred = np.polyval(coeffs, X)
    mse = np.mean((y - y_pred) ** 2)
    errors.append(mse)

plt.plot(degrees, errors, marker='o')
plt.xlabel("Model Complexity (Degree)")
plt.ylabel("Training Error")
plt.title("Error vs Complexity")
plt.show()

import numpy as np

def calculate_mse(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

y_true = np.array([10, 20, 30])
y_pred = np.array([12, 18, 33])

print(calculate_mse(y_true, y_pred))

import numpy as np
import matplotlib.pyplot as plt
X = np.linspace(0, 10, 50)
y = 2 * X + 3 + np.random.randn(50)

coeffs = np.polyfit(X, y, 1)
y_pred = np.polyval(coeffs, X)

plt.scatter(X, y)
plt.plot(X, y_pred, color='red')
plt.title("Regression")
plt.show()

X = np.linspace(0, 10, 50)
y = np.where(X > 5, 1, 0)

plt.scatter(X, y)
plt.title("Classification")
plt.show()

X = np.linspace(0, 10, 30)
y = np.sin(X) + np.random.randn(30)*0.3

y1 = np.polyval(np.polyfit(X, y, 1), X)
y5 = np.polyval(np.polyfit(X, y, 5), X)

plt.scatter(X, y)
plt.plot(X, y1, label="Underfit")
plt.plot(X, y5, label="Overfit")
plt.legend()
plt.title("Bias-Variance")
plt.show()