# -*- coding: utf-8 -*-
"""assignment_21_am.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mSf8ASU7CgmxWWVVz157lpAST8sVqMT5
"""

import numpy as np


arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr3 = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

print(arr1)
print(arr2)
print(arr3)

print(arr1[2])
print(arr1[1:4])

print(arr2[1, 2])
print(arr2[0])
print(arr2[:, 1])
print(arr2[0:2, 1:3])


print(arr3[0, 1, 1])

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


print(a + b)
print(a - b)
print(a * b)

print(np.mean(a))
print(np.var(a))
print(np.std(a))

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr1 = np.array([10, 20, 30])

print(arr2 + arr1)

print(arr2 * 2)

vec = np.array([1, 2, 3])
print(arr2 * vec)

vec = np.array([1, 2, 3])
print(arr2 * vec)

arr = np.array([-2, -1, 0, 1, 2, 3])

print(arr**2)
print(arr**3)
arr[arr < 0] = 0
print(arr)

arr = np.array([10, 20, 30, 40])
norm = (arr - arr.min()) / (arr.max() - arr.min())
print(norm)

data = np.array([10, 50, 30, 20, 90, 60, 80, 70])

top5 = np.sort(data)[-5:]
print(top5)

data2 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(np.sum(data2, axis=1))

print(np.sum(data2, axis=0))

threshold = 5
indices = np.where(data2 > threshold)
print(indices)

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.dot(A, B))
print(A.T)
print(np.linalg.det(A))

A = np.array([[2, 1],
              [1, 3]])

B = np.array([5, 6])

solution = np.linalg.solve(A, B)
print(solution)

import time
import numpy as np

arr = np.random.rand(1000000)

start = time.time()
total = 0
for i in arr:
    total += i
end = time.time()
print("Loop time:", end - start)

start = time.time()
total_np = np.sum(arr)
end = time.time()
print("NumPy time:", end - start)

import numpy as np

def normalize(X):
  return (X - np.min(X)) / (np.max(X) - np.min(X))

X = np.array([10, 20, 30, 40])
print(normalize(X))

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

result = A + B
print(result)

import numpy as np

arr = np.array([1, 2, 3, 4])

result = arr ** 2
print(result)

result = []
for i in arr:
    result.append(i**2)

print(result)





